log_dir: ${name}/
resume:

experiment_name: MnistExample

metrics:
  - _target_: src.model.metric.accuracy
  - _target_: src.model.metric.top_k_acc

defaults:
  - data: mnist_train
  - model: mnist_lenet
  - hparams: lenet_baseline

  - status: train

  - hydra/job_logging : custom
  - hydra/run/dir: job_timestamp